###空間分析　 作業2
####地理二　B06208001　龔泓愷

> Q2：繪製一張圖表，比較各行政區的麥當勞與肯德基在90-99年的規模變遷趨勢；並解釋其圖表呈現的意涵。

```{r results='hide', message = F, warning = F}
library(ggplot2)
library(rgdal)
library(tidyr)
library(dplyr)
FastFood <- readOGR(dsn = "./data", layer = "Tpe_Fastfood", encoding="utf8")
```
```{r warning = F}
data <- FastFood@data
# change from factor to numeric
data$TYPE_90 <- as.numeric(as.character(data$TYPE_90))
data$TYPE_99 <- as.numeric(as.character(data$TYPE_99))
# calculate the change
data$CHANGE <- (data$TYPE_99 - data$TYPE_90)
# assign larger smaller or the same
data_done <- data %>%
  mutate(STATUS = case_when(
    STORE == 'KFC' & CHANGE < 0 ~ 'kfc_small',
    STORE == 'KFC' & CHANGE == 0 ~ 'kfc_same',
    STORE == 'KFC' & CHANGE > 0 ~ 'kfc_large',
    STORE == 'MIC' & CHANGE < 0 ~ 'mic_small',
    STORE == 'MIC' & CHANGE == 0 ~ 'mic_same',
    STORE == 'MIC' & CHANGE > 0 ~ 'mic_large'
  ))
#plot
ggplot(data_done, aes(x = TOWN, fill = STATUS)) +
  geom_bar() +
  scale_x_discrete('行政區') + scale_y_continuous('間數') +
  scale_fill_manual('銷售規模變化', labels = c('肯德基 提升', '肯德基 持平', '肯德基 減少', '麥當勞 增加', '麥當勞 持平', '麥當勞 減少'), values = c('#6495ED', '#66CDAA', '#F08080', '#4682B4', '#008080', '#DC143C')) +
  ggtitle('台北市各行政區速食店銷售規模變化趨勢圖')
```

從上圖看來，首先能注意到除了文山區多數的麥當勞為銷售規模減少外，其他行政區的麥當勞增加或持平佔了多數。    
肯德基的部分，除了中山與松山區部分店家銷售規模縮減之外，其他地區的肯德基皆為持平與增加。    
最後，從顏色的分布我們也能看出，台北市麥當勞的間數明顯多於肯德基。    